name: Build - macOS

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['src/**', 'cmake/**', 'browser/**', 'modules/**', 'mods/**', 'data/**', 'init.lua', 'config.ini', 'otclientrc.lua', 'CMakeLists.txt', 'CMakePresets.json', 'vcpkg.json', '.github/workflows/build-platforms.yml', '.github/workflows/build-macos.yml']
  pull_request:
    paths: ['src/**', 'cmake/**', 'browser/**', 'modules/**', 'mods/**', 'data/**', 'init.lua', 'config.ini', 'otclientrc.lua', 'CMakeLists.txt', 'CMakePresets.json', 'vcpkg.json', '.github/workflows/build-platforms.yml', '.github/workflows/build-macos.yml']

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-platforms.yml
    with:
      platform: macos
